### ISSUE TITLE
IOError: [Errno 2] No such file or directory: in faceMorph.py 

### ISSUE THREAD

**Issue by jasch-shah** [spmallick/learnopencv#162]
Traceback (most recent call last):
  File "faceMorph.py", line 84, in <module>
    points1 = readPoints(filename1 + '.txt')
  File "faceMorph.py", line 10, in readPoints
    with open(path) as file :
IOError: [Errno 2] No such file or directory: 'hillary_clinton.txt'

**Comment by vishwesh5** [comment]
Can you try and run the code again? Let me know if it doesn't work.
