### ISSUE TITLE
python-issue : not enough values to unpack

### ISSUE THREAD

**Issue by JacJachin** [spmallick/learnopencv#188]
Traceback (most recent call last):
  File "mask_rcnn.py", line 161, in <module>
    postprocess(boxes, masks)
  File "mask_rcnn.py", line 85, in postprocess
    drawBox(frame, classId, score, left, top, right, bottom, classMask)
  File "mask_rcnn.py", line 48, in drawBox
    im2, contours, hierarchy = cv.findContours(mask,cv.RETR_TREE,cv.CHAIN_APPROX_SIMPLE)
**ValueError: not enough values to unpack (expected 3, got 2)**

when i run this program with python,this issue occur,then 
i find this code in line 48: 
im2, contours, hierarchy = cv.findContours(mask, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
and i delete the "im2" variable ,then this program runs normally.
contours, hierarchy = cv.findContours(mask, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

**Comment by krshrimali** [comment]
This is most probably because of your OpenCV Version. 

In OpenCV 3.4.4-dev `findContours()` function returns modified image as well. While in OpenCV 4.0.0-dev `findContours()` function doesn't return the modified image.

Check out the below links for more information: 

1. **OpenCV 3.4.4-dev:** https://docs.opencv.org/3.4/d4/d73/tutorial_py_contours_begin.html
2. **OpenCV 4.0.0-dev:** https://docs.opencv.org/master/d4/d73/tutorial_py_contours_begin.html

**Comment by JianpingCAI** [comment]
I had the same issue with OpenCV 4.0.0, and 3.4.4.19 works for me.

**Comment by asmorkalov** [comment]
Fixed in https://github.com/spmallick/learnopencv/pull/466.
