### ISSUE TITLE
openimages downloader error

### ISSUE THREAD

**Issue by richipower** [spmallick/learnopencv#250]
Hello i was trying the script to download the openimages dataset.. but i get this error:

Traceback (most recent call last):
  File "downloadOI.py", line 46, in <module>
    subprocess.run(['rm', '-rf', run_mode])
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

I am trying it under windows..

thanks!

**Comment by the-black-boy** [comment]
i had the same problem on windows 10

Traceback (most recent call last):
  File "downloadOI.py", line 39, in <module>
    subprocess.run('rm -rf run_mode')
  File "C:\Users\BlackBoy\Anaconda3\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\BlackBoy\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\BlackBoy\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by LarryK348** [comment]
I'm having the same issue. Has anyone successfully used downloadOI.py on Windows?

**Comment by JWStone** [comment]
I think the issue is that rm and mkdir are a linux commands.  We need the del /f/s and cd commands for Windows instead.  
subprocess.run(['del', '/f/s', run_mode],shell=True)
subprocess.run(['cd', run_mode],shell=True)

Not sure yet what to do about command.split().

**Comment by LarryK348** [comment]
I sent a fix to Vishwesh.
It’s attached.

Larry

[ac logo]
marcom, creative services, web & software development
Larry Kimminau
408.483.4078
http://www.analyticconcepts.com<http://www.analyticconcepts.com/>

**Comment by Bingobbb** [comment]
you could try to replace "shell = True" with “shell = false” in  
subprocess.py->class Popen(object) ->def __init__(...,shell = false,...)

**Comment by Bingobbb** [comment]
you could try to replace "shell = False" with “shell = True” in
subprocess.py->class Popen(object) ->def init(...,shell = False,...)
