### ISSUE TITLE
accumulated_exposures = np.zeros((frame.shape[0], frame.shape[1]), dtype=np.float) AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by garimss** [spmallick/learnopencv#322]
processing visa_frames/8293.jpg
Traceback (most recent call last):
  File "generate_heatmap.py", line 185, in <module>
    main()
  File "generate_heatmap.py", line 133, in main
    accumulated_exposures = np.zeros((frame.shape[0], frame.shape[1]), dtype=np.float)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by garimss** [comment]
solved, change the path in labels.txt
