### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by aliYaHf** [spmallick/learnopencv#327]
hi, i use the image classification code , but i have the error, can you help me?
``1
{0: 'cat', 1: 'dog'}
Traceback (most recent call last):

  File "<ipython-input-18-3e86a14cab7d>", line 1, in <module>
    runfile('/home/liu/kaggle/untitled1.py', wdir='/home/liu/kaggle')
  File "/home/liu608/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)
  File "/home/liu608/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/home/liu608/kaggle/untitled1.py", line 115, in <module>
    resnet50 = resnet50.to('cuda:0')
  File "/home/liu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/home/liu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/liu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)

  File "/home/liu/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: device-side assert triggered

**Comment by reda-maizate** [comment]
Hey, I had the same problem than you. This post (https://towardsdatascience.com/cuda-error-device-side-assert-triggered-c6ae1c8fa4c3) solved mine, I hope it'll solve yours.
