### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by i170326** [spmallick/learnopencv#504]
I am trying to run: python getDataFromOpenImages_snowman.py to download the data, but I am getting this error. 

I have both the .csv files in the same folder as getDataFromOpenImages_snowman.py files as per https://www.learnopencv.com/training-yolov3-deep-learning-based-custom-object-detector/

- Windows 10 
- Python 3.8.5

Here's what I am getting:

Traceback (most recent call last):
  File "getDataFromOpenImages_snowman.py", line 12, in <module>
    subprocess.run(['rm', '-rf', 'JPEGImages'])
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\HP\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by pkop28** [comment]
Hello
I am having the same issue. Did you figure out a way to resolve it?

Greetings,
pkop28
