### ISSUE TITLE
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by RobbyGit** [spmallick/learnopencv#696]
Hi 

I cant get the yolov5.py to work. 

This is the error I get:

```
Traceback (most recent call last):
  File "main.py", line 125, in <module>
    img = post_process(frame.copy(), detections)
  File "main.py", line 72, in post_process
    if confidence >= CONFIDENCE_THRESHOLD:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
I am using:
Python 3.8.10
Ubuntu 20.04.4 LTS
opencv-python-4.5.4.60

I am not that great at Python and learning and I think the error has something to do with if confidence >= CONFIDENCE_THRESHOLD being a list

Thanks

Robby

**Comment by chunxiao3600** [comment]
I also have the same problem:
Traceback (most recent call last):
  File "/Users/abc/PycharmProjects/yolo/yolov5/fps.py", line 124, in <module>
    img = post_process(frame.copy(), detections)
  File "/Users/abc/PycharmProjects/yolo/yolov5/fps.py", line 71, in post_process
    if confidence >= CONFIDENCE_THRESHOLD:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
