### ISSUE TITLE
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'

### ISSUE THREAD

**Issue by Weston-yuan** [spmallick/learnopencv#761]
When I run the last code `!python app.py` 
Then the warning appear
`
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from src.lstm import ActionClassificationLSTM
  File "/content/learnopencv/Human-Action-Recognition-Using-Detectron2-And-Lstm/src/lstm.py", line 4, in <module>
    import pytorch_lightning as pl
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/__init__.py", line 20, in <module>
    from pytorch_lightning import metrics  # noqa: E402
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py", line 15, in <module>
    from pytorch_lightning.metrics.classification import (  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/__init__.py", line 14, in <module>
    from pytorch_lightning.metrics.classification.accuracy import Accuracy  # noqa: F401
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/classification/accuracy.py", line 18, in <module>
    from pytorch_lightning.metrics.utils import deprecated_metrics
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/utils.py", line 22, in <module>
    from torchmetrics.utilities.data import get_num_classes as _get_num_classes
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data' (/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/data.py)
`

Any suggestions?

**Comment by brmarkus** [comment]
Which sample, which application are you referencing?
Which environment using which versions of the requirements have you installed?
(the samples in this repo are maintained not so frequently, they can become outdated quickly with the frequent updates of the operating systems, updates of Pytorch, etc.)

**Comment by Weston-yuan** [comment]
I referencing the sample Human Action Recognition using Detectron2 and LSTM, 
and use the the colab notebook: 
https://colab.research.google.com/drive/1mr3wJUeS1mFJVgMoo3TgnyMSmwPtwCvR?usp=sharing 
Thanks

**Comment by brmarkus** [comment]
Can you try with a clean environment (e.g. on your local machine, using a Python-virtual-env), again?
In your shared Colab I see a few errors (e.g. "destination path 'learnopencv' already exists and is not an empty directory.", "tensorflow 2.5.0 requires tensorboard~=2.5, but you have tensorboard 2.4.1 which is incompatible")

**Comment by Heeran-cloud** [comment]
It happened to me when my PC had dependencies issue. For the temporary approach, you would be ok to downgrade torchmetrics==0.6.0. But, you would end up being reinstall the virtual environment in your PC or restart the runtime in Colab to install every package you need for this set up. (i.e.) requirements.txt.
