### ISSUE TITLE
TypeError: plot_skeleton_kpts() missing 2 required positional arguments: 'kpts' and 'steps

### ISSUE THREAD

**Issue by csnam** [spmallick/learnopencv#907]
**I tried following "yolov7-pose-vs-mediapipe-in-human-pose-estimation", but the following error occurred. Can anyone help me?
Do I need to change part of the source?**

TypeError: plot_skeleton_kpts() missing 2 required positional arguments: 'kpts' and 'steps'

```
(yolov7_pose) PS E:\Project\YOLOProject\yolov7> python .\yolov7-pose.py
Selected Device :  cpu
(192, 256, 3)
E:\Project\YOLOProject\yolov7-pose-estimation\yolov7_pose\lib\site-packages\torch\functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3550.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Traceback (most recent call last):
  File ".\yolov7-pose.py", line 103, in <module>
    img, fps_ = pose_video(frame)
  File ".\yolov7-pose.py", line 46, in pose_video
    plot_skeleton_kpts(nimg, output[idx, 7:].T, 3)
TypeError: plot_skeleton_kpts() missing 2 required positional arguments: 'kpts' and 'steps'
```

**Comment by csnam** [comment]
You are right. Thanks for your advice.
I followed the blog and test it. If you use the original, there will be no error.
There was no need to change anything to test a simple video.
thank you much

`
> Clone the YOLOv7 repository and put yolov7-pose.py in the root directory.
> Replace yolov7/utils/plots.py with our version of plots.py.
`

**Comment by csnam** [comment]
You are right. Thanks for your advice. I followed the blog and test it. If you use the original, there will be no error. There was no need to change anything to test a simple video. thank you much
 
 `
 Clone the YOLOv7 repository and put yolov7-pose.py in the root directory.

 Replace yolov7/utils/plots.py with our version of plots.py.
 `
